NorthWindExampleApp4/Models/Customers.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace NorthWindExampleApp4.Models;

public partial class Customers
{
    /// <summary>
    /// Primary key
    /// </summary>
    public int CustomerIdentifier { get; set; }
    [Display(Name = "Name")]
    public string CompanyName { get; set; }

    public int? ContactId { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    [Display(Name = "Postal")]
    public string PostalCode { get; set; }

    public int? CountryIdentifier { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public int? ContactTypeIdentifier { get; set; }
    [Display(Name = "Modified")]
    public DateTime? ModifiedDate { get; set; }

    public virtual Contacts Contact { get; set; }
    [Display(Name = "Contact type id")]
    public virtual ContactType ContactTypeIdentifierNavigation { get; set; }

    public virtual Countries CountryIdentifierNavigation { get; set; }

    public virtual ICollection<Orders> Orders { get; } = new List<Orders>();
}

NorthWindExampleApp4/Pages/CustomerView.cshtml.cs
using EntityFrameworkLibrary;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NorthWindExampleApp4.Classes;
using NorthWindExampleApp4.Data;
using NorthWindExampleApp4.Models;

namespace NorthWindExampleApp4.Pages
{
    public class CustomerViewModel : PageModel
    {
        private readonly Context _context;

        public CustomerViewModel(Context context)
        {
            _context = context;
        }
        public string NameSort { get; set; }
        public string CurrentSort { get; set; }
        public IList<Customers> Customers { get;set; } = default!;

        public SelectList ColumnList { get; set; }
        [BindProperty]
        public List<SqlColumn> SqlColumns { get; set; }

        [BindProperty]
        public int SelectedIndex { get; set; }

        /// <summary>
        /// Shows how to do a sort via  asp-route and via select input from post event
        /// </summary>
        /// <param name="sortOrder">column name</param>
        public async Task OnGetAsync(string sortOrder)
        {
            if (_context.Customers != null)
            {
                if (!string.IsNullOrWhiteSpace(sortOrder))
                {
                    Customers = await OrderByOnNavigation(sortOrder);
                }
                else
                {
                    Customers = await GetCustomers();
                }
                
                SqlColumns = _context.GetModelProperties("Customers");
                ColumnList = new SelectList(SqlColumns, "Id", "Name");
            }
        }

        public async Task OnPostSubmit(int id)
        {
            SqlColumns = _context.GetModelProperties("Customers");
            var current = SqlColumns.FirstOrDefault(x => x.Id == id);
            if (current!.IsNavigation)
            {
                Customers = await OrderByOnNavigation(current.NavigationValue);
            }
            else
            {
                Customers = await OrderByOnNavigation(current.Name);
            }

            ColumnList = new SelectList(SqlColumns, "Id", "Name");
            SelectedIndex = id;
            ViewData["JavaScript"] = id;
        }

        public async Task<List<Customers>> OrderByOnNavigation(string ordering)
        {

            return await _context.Customers
                .Include(c => c.CountryIdentifierNavigation)
                .Include(c => c.Contact)
                .Include(c => c.ContactTypeIdentifierNavigation)
                .OrderByColumn(ordering)
                .ToListAsync();

        }

        public async Task<List<Customers>> GetCustomers()
        {

            return await _context.Customers
                .Include(c => c.CountryIdentifierNavigation)
                .Include(c => c.Contact)
                .Include(c => c.ContactTypeIdentifierNavigation)
                .ToListAsync();

        }
    }
}

NorthWindExampleApp4/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace NorthWindExampleApp4.Pages;
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

NorthWindExampleApp4/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NorthWindExampleApp4.Pages;
public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

NorthWindExampleApp4/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NorthWindExampleApp4.Pages;
public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

NorthWindExampleApp4/Pages/CustomerView.cshtml
@page
@model NorthWindExampleApp4.Pages.CustomerViewModel

@{
    ViewData["Title"] = "Customers";
}

<h1 class="fs-4">Customers</h1>
<form method="post">
    <input id="selectedIndex" type="hidden" asp-for="SelectedIndex" />
    <div class="row mb-4 mt-4">
        <div class="col-md-3">
            <select id="modelColumns" name="Id" class="form-select" asp-items="@Model.ColumnList">
            </select>

        </div>
        <div class="col-6">
            <input type="submit" class="btn btn-outline-dark" value="Order by" asp-page-handler="Submit" />
        </div>
    </div>
</form>


<table class="table table-striped table-primary">
    <thead>
        <tr>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="CompanyName">
                    @Html.DisplayNameFor(model => model.Customers[0].CompanyName)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="Street">
                    @Html.DisplayNameFor(model => model.Customers[0].Street)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="City">
                    @Html.DisplayNameFor(model => model.Customers[0].City)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="Region">
                    @Html.DisplayNameFor(model => model.Customers[0].Region)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="PostalCode">
                    @Html.DisplayNameFor(model => model.Customers[0].PostalCode)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="Phone">
                    @Html.DisplayNameFor(model => model.Customers[0].Phone)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="Fax">
                    @Html.DisplayNameFor(model => model.Customers[0].Fax)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="ModifiedDate">
                    @Html.DisplayNameFor(model => model.Customers[0].ModifiedDate)
                </a>
            </th>
            <th>
                
                <a asp-page="/CustomerView" asp-route-sortOrder="Contact.LastName">
                    @Html.DisplayNameFor(model => model.Customers[0].Contact.Name)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="ContactTypeIdentifierNavigation.ContactTitle">
                    @Html.DisplayNameFor(model => model.Customers[0].ContactTypeIdentifierNavigation.ContactTitle)
                </a>
            </th>
            <th>
                <a asp-page="/CustomerView" asp-route-sortOrder="CountryIdentifierNavigation.Name">
                    @Html.DisplayNameFor(model => model.Customers[0].CountryIdentifierNavigation.Name)
                </a>
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Customers)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Street)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Region)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PostalCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Fax)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contact.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactTypeIdentifierNavigation.ContactTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CountryIdentifierNavigation.Name)
                </td>

            </tr>
        }
    </tbody>
</table>



@section Scripts {

    <script>
        document.addEventListener("DOMContentLoaded", () => {
            if (localStorage.getItem("columnIndex") !== null) {
                document.getElementById("modelColumns").selectedIndex = parseInt(localStorage.getItem("columnIndex"));
            }
        });
        $('form').submit(function (event) {
            localStorage.setItem("columnIndex", document.getElementById("modelColumns").selectedIndex);
        });

    </script>
}

NorthWindExampleApp4/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}